"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnitSupportProduction = exports.UnitSupportFood = exports.Unhappiness = exports.Trade = exports.Research = exports.Production = exports.PopulationUnhappiness = exports.PopulationSupportFood = exports.MilitaryUnhappiness = exports.MartialLaw = exports.LuxuryHappiness = exports.Luxuries = exports.Happiness = exports.Gold = exports.FoodStorage = exports.Food = exports.Corruption = exports.CityImprovementMaintenanceGold = exports.CityImprovementContent = void 0;
var CityImprovementContent_1 = require("./Yields/CityImprovementContent");
Object.defineProperty(exports, "CityImprovementContent", { enumerable: true, get: function () { return CityImprovementContent_1.CityImprovementContent; } });
var CityImprovementMaintenanceGold_1 = require("./Yields/CityImprovementMaintenanceGold");
Object.defineProperty(exports, "CityImprovementMaintenanceGold", { enumerable: true, get: function () { return CityImprovementMaintenanceGold_1.CityImprovementMaintenanceGold; } });
var Corruption_1 = require("./Yields/Corruption");
Object.defineProperty(exports, "Corruption", { enumerable: true, get: function () { return Corruption_1.Corruption; } });
var Food_1 = require("./Yields/Food");
Object.defineProperty(exports, "Food", { enumerable: true, get: function () { return Food_1.Food; } });
var FoodStorage_1 = require("./Yields/FoodStorage");
Object.defineProperty(exports, "FoodStorage", { enumerable: true, get: function () { return FoodStorage_1.FoodStorage; } });
var Gold_1 = require("./Yields/Gold");
Object.defineProperty(exports, "Gold", { enumerable: true, get: function () { return Gold_1.Gold; } });
var Happiness_1 = require("./Yields/Happiness");
Object.defineProperty(exports, "Happiness", { enumerable: true, get: function () { return Happiness_1.Happiness; } });
var Luxuries_1 = require("./Yields/Luxuries");
Object.defineProperty(exports, "Luxuries", { enumerable: true, get: function () { return Luxuries_1.Luxuries; } });
var LuxuryHappiness_1 = require("./Yields/LuxuryHappiness");
Object.defineProperty(exports, "LuxuryHappiness", { enumerable: true, get: function () { return LuxuryHappiness_1.LuxuryHappiness; } });
var MartialLaw_1 = require("./Yields/MartialLaw");
Object.defineProperty(exports, "MartialLaw", { enumerable: true, get: function () { return MartialLaw_1.MartialLaw; } });
var MilitaryUnhappiness_1 = require("./Yields/MilitaryUnhappiness");
Object.defineProperty(exports, "MilitaryUnhappiness", { enumerable: true, get: function () { return MilitaryUnhappiness_1.MilitaryUnhappiness; } });
var PopulationSupportFood_1 = require("./Yields/PopulationSupportFood");
Object.defineProperty(exports, "PopulationSupportFood", { enumerable: true, get: function () { return PopulationSupportFood_1.PopulationSupportFood; } });
var PopulationUnhappiness_1 = require("./Yields/PopulationUnhappiness");
Object.defineProperty(exports, "PopulationUnhappiness", { enumerable: true, get: function () { return PopulationUnhappiness_1.PopulationUnhappiness; } });
var Production_1 = require("./Yields/Production");
Object.defineProperty(exports, "Production", { enumerable: true, get: function () { return Production_1.Production; } });
var Research_1 = require("./Yields/Research");
Object.defineProperty(exports, "Research", { enumerable: true, get: function () { return Research_1.Research; } });
var Trade_1 = require("./Yields/Trade");
Object.defineProperty(exports, "Trade", { enumerable: true, get: function () { return Trade_1.Trade; } });
var Unhappiness_1 = require("./Yields/Unhappiness");
Object.defineProperty(exports, "Unhappiness", { enumerable: true, get: function () { return Unhappiness_1.Unhappiness; } });
var UnitSupportFood_1 = require("./Yields/UnitSupportFood");
Object.defineProperty(exports, "UnitSupportFood", { enumerable: true, get: function () { return UnitSupportFood_1.UnitSupportFood; } });
var UnitSupportProduction_1 = require("./Yields/UnitSupportProduction");
Object.defineProperty(exports, "UnitSupportProduction", { enumerable: true, get: function () { return UnitSupportProduction_1.UnitSupportProduction; } });
//# sourceMappingURL=Yields.js.map